exports.mainQuestsInfo = {
  title: "Main Quest Line",
  quests: [
    "Unbound",
    "Before the Storm",
    "Bleak Falls Barrow",
    "Dragon Rising",
    "The Way of The Voice",
    "The Horn of Jurgen Windcaller",
    "A Blade In The Dark",
    "Diplomatic Immunity",
    "A Cornered Rat",
    "Alduin's Wall",
    "The Throat of The World",
    "Elder Knowledge",
    "Alduin's Bane",
    "Season Unending",
    "The Fallen",
    "Paarthurnax",
    "The World-Eater's Eyrie",
    "Sovngarde",
    "Dragonslayer",
  ],
  questDesc: [
    "Escape Helgen",
    "Warn the Jarl of Whiterun",
    "Retrieve the Dragonstone",
    "Slay your first Dragon",
    "Meet with the Greybeards",
    "Recover the Horn from Ustengrav",
    "Prove to Delphine you are Dragonborn",
    "Infiltrate the Thalmor Embassy",
    "Find Esbern in the Ratway",
    "Find Sky Haven Temple",
    "Learn Clear Skies to talk to Paarthurnax",
    "Recover the Elder Scroll",
    "Use Dragonrend to defeat Alduin",
    "Negotiate a truce to halt the Civil War",
    "Capture Odahviing in Dragonsreach",
    "Kill or Spare Paarthurnax",
    "Enter the portal to Sovngarde",
    "Gain admittance to the Hall of Valor",
    "Defeat Alduin For Good",
  ],
};

exports.darkBrotherhoodQuestsInfo = {
  title: "Dark Brotherhood",
  quests: [
    "Delayed Burial",
    "Innocence Lost",
    "With Friends Like These...",
    "Sanctuary",
    "Mourning Never Comes",
    "Whispers In The Dark",
    "The Silence Has Been Broken",
    "Bound Until Death",
    "Breaching Security",
    "The Cure for Madness",
    "Recipe for Disaster",
    "The Kill an Empire",
    "Death Incarnate",
    "Hail Sithis!",
    "Contract: Kill Beitild",
    "Contract: Kill Narfi",
    "Contract: Kill Ennodius Papius",
    "Contract: Kill Lurbuk",
    "Contract: Kill Hern",
    "Contract: Kill Deekus",
    "Contract: Kill Ma'randru-jo",
    "Contract: Kill Anoriath",
    "Contract: Kill Agnis",
    "Contract: Kill Maluril",
    "Contract: Kill Helvard",
    "Contract: Kill Safia",
    "Locate The Assassins of Old",
    "Honor Thy Family",
    "Dark Brotherhood Forever",
    "Destroy The Dark Brotherhood!",
    "Where You hang Your Enemy's Head",
  ],
  questDesc: [
    "Help Cicero or have him arrested",
    "Kill Grelod the Kind",
    "Choose which captives to kill",
    "Speak with Nazir",
    "Kill Alain Dufont",
    "Investigate Cicero",
    "Meet with Amaund Motierre",
    "Kill Vittoria Vici",
    "Kill Gaius Maro",
    "Deal with Cicero",
    "Kill The Gourmet and take his place",
    "Kill the Emperor and escape",
    "Rescue Nazir and kill Astrid",
    "Finish the contract on The Emperor",
    "Complete the Contract",
    "Complete the Contract",
    "Complete the Contract",
    "Complete the Contract",
    "Complete the Contract",
    "Complete the Contract",
    "Complete the Contract",
    "Complete the Contract",
    "Complete the Contract",
    "Complete the Contract",
    "Complete the Contract",
    "Complete the Contract",
    "Locate the ancient assassin",
    "Gain re-admittance to the Dark Brotherhood",
    "Complete the Night Mother contract",
    "Kill everyone in the Dark Brotherhood",
    "Upgrade the Dawnstar Sanctuary",
  ],
};

exports.collegeWinterholdQuestsInfo = {
  title: "College of Winterhold",
  quests: [
    "First Lessons",
    "Under Saarthal",
    "Hitting The Books",
    "Good Intentions",
    "Revealing the Unseen",
    "Containment",
    "The Staff of Magnus",
    "The Eye of Magnus",
    "Alteration Ritual Spell",
    "Conjuration Ritual Spell",
    "Destruction Ritual Spell",
    "Illusion Ritual Spell",
    "Restoration Ritual Spell",
    "Arniel's Endeavor",
    "Out of Balance",
    "J'zargo's Experiment",
    "Onmund's Request",
    "Brelyna's Practice",
    "Rejoining The College",
    "Forgotten Names",
    "Fetch Me That Book!",
    "Shalidor's Insights",
    "Aftershock",
    "Tolfdir The Absent-Minded",
    "Enchanting Pick-Up",
    "Restocking Soul Gems",
  ],
  questDesc: [
    "Join the College of Winterhold",
    "Explore Saarthal with the class",
    "Find the stolen books",
    "Find the Augur of Dunlain",
    "Explore the ruins of Mzulft",
    "Protect the Town of Winterhold",
    "Retrieve the Staff of Magnus",
    "Defeat Ancano",
    "Learn the Master Alteration Spell",
    "Learn the Master Conjuration Spell",
    "Learn the Master Destruction Spell",
    "Learn the Master Illusion Spell",
    "Learn the Master Restoration Spell",
    "Assist Arniel's Experiment",
    "Cleanse the magical focal points",
    "Test J'zargo's scrolls",
    "Retrieve the family amulet",
    "Help Brelyna test spells",
    "Speak to Tolfdir to rejoin",
    "Slay or release Velehk Sain",
    "Find books for Urag gro-Shub",
    "Find Shalidor's writings",
    "Close the rupture",
    "Find Tolfdir's Alembic",
    "Deliver item to Sergius Turrianus",
    "Deliver soul gems to Sergius Turrianus",
  ],
};

exports.companionsQuestsInfo = {
  title: "Companions",
  quests: [
    "Take Up Arms",
    "Proving Honor",
    "The Silver Hand",
    "Blood's Honor",
    "Purity of Revenge",
    "Glory of the Dead",
    "Animal Extermination",
    "Hired Muscle",
    "Trouble in Skyrim",
    "Family Heirloom",
    "Escaped Criminal",
    "Rescue Mission",
    "Stealing Plans",
    "Striking the Heart",
    "Retrieval",
    "Totems of Hircine",
    "Purity",
    "Dragon Seekers",
  ],
  questDesc: [
    "Speak with the leader of the Companions",
    "Retrieve a fragment of Wuuthrad",
    "Participate in the blood ritual",
    "Collect Glenmoril Witch head",
    "Recover stolen fragments of Wuuthrad",
    "Cleanse Kodlak Whitemane",
    "Kill the beast",
    "Intimidate the target",
    "Kill the leader of the group",
    "Retrieve the heirloom",
    "Kill the escaped criminal",
    "Rescue and escort the victim",
    "Steal the plans",
    "Assassinate Silver Hand leader",
    "Retrieve a fragment of Wuuthrad",
    "Retrieve the totem of Hircine",
    "Cleanse the quest giver of beastblood",
    "Kill the dragon at the den",
  ],
};

exports.thievesGuildQuestInfo = {
  title: "Thieves Guild",
  quests: [
    "A Chance Arrangement",
    "Taking Care of Business",
    "Loud and Clear",
    "Dampened Spirits",
    "Scoundrel's Folly",
    "Speaking With Silence",
    "Hard Answers",
    "The Pursuit",
    "Trinity Restored",
    "Blindsighted",
    "Darkness Returns",
    "Under New Management",
    "Imitation Amnesty",
    "Summerset Shadows",
    "Silver Lining",
    "The Dainty Sload",
    "Delivery",
    "No Stone Unturned",
  ],
  questDesc: [],
};

exports.bladesQuestsInfo = {
  title: "Blades",
  quests: ["Paarthurnax", "Rebuilding the Blades", "Dragon Hunting"],
  questDesc: [
    "Kill or spare Paarthurnax",
    "Initiate three new Blades",
    "Defeat the dragon",
  ],
};

exports.bardsCollegeQuestsInfo = {
  title: "Bards College",
  quests: [
    "Tending the Flames",
    "Find Rjorn's Drum",
    "Find Finn's Lute",
    "Find Pantea's Flute",
  ],
  questDesc: [
    "Find King Olaf's verse",
    "Retrieve the drum",
    "Retrieve the Lute",
    "Retrieve the Flute",
  ],
};
